### ISSUE TITLE
example data provide

### ISSUE THREAD

**Issue by wangtao1321** [desh2608/crnn-relation-classification#1]
Hello：
    I want to run your models to learn how CRNN works,can you provide some test datasets or examples if your full dataset unsuitable for public？ Thanks！

**Comment by desh2608** [comment]
Unfortunately both the i2b2 and DDI datasets are not available to be shared freely, although you can mail them directly to ask for it. You can try the model on any freely available sentence classification/relation classification/sentiment analysis data. This is a popular data for sentiment analyis: https://www.kaggle.com/c/sentiment-analysis-on-movie-reviews
