### ISSUE TITLE
hello,I think i got some trouble

### ISSUE THREAD

**Issue by lyfree132** [desh2608/crnn-relation-classification#2]
hello,I want to repeat your experiment,but there is missing some files.Can you upload the data you need for the experiment?Thank you very much.

**Comment by desh2608** [comment]
Unfortunately both the i2b2 and DDI datasets are not available to be shared freely, as per license agreements. You may contact the original distributors of both datasets. See this link (https://www.i2b2.org/NLP/DataSets/Main.php) for the i2b2 data, and here (http://labda.inf.uc3m.es/doku.php?id=en:labda_ddicorpus) for the DDI dataset.

The architecture itself is generic and you can apply it to any relation classification dataset with minor tweaks in preprocessing (taking cues from the preprocess.py file).

**Comment by lyfree132** [comment]
What I see in preprocess.py is the following training set: 
##Processing the training set
fp_train = open ('./i2b2/80-20/i2b2-80-enttype.train','r'), but I don't know much about the format of this data. I've been applying for this dataset, but it hasn't been answered yet.Can you paste a sample data? I just want to see the format of the data.thank you.

**Comment by desh2608** [comment]
The data is in this format:

ata/test/0106._121
With intravenous hydration the BUN and creatinine fell to 12/1.9 which is within normal limits for this patient .
(['intravenous hydration', 1, 2, 'treatment'], ['creatinine', 6, 6, 'test'])
[0]

Sentence ID
Sentence
Entities with their position and type
Label
