### ISSUE TITLE
This implementation should be revised ?

### ISSUE THREAD

**Issue by lasso007** [desh2608/crnn-relation-classification#3]
I am not sure that I misunderstand author's idea.

According to the paper "Learning local and global contexts using a convolutional recurrent network model for relation classification in biomedical text (Desh Raj, Sunil Kumar Sahu, and Ashish Anand)".  In the file "crnn-relation-classification/source/crnn-att.py",
>  h2_pool =  tf.matmul(alpha, h2_cnn, name="r")

should be revised, I think, as follow:

> h2_pool =  tf.matmul(alpha, tf.reshape(h1_cnn, shape=[-1, seq_len-(filter1_size-1)-(filter2_size-1), num_filters2]), name="r")

And the activation should be "tanh" funcation.

**Comment by desh2608** [comment]
Thanks for pointing out the issue. Indeed it should be as you have mentioned. I'll revise the implementation.

**Comment by desh2608** [comment]
At the same time, though, it wouldn't make much of a difference in the architecture or the convergence whether the attention is multiplied with the original output of the convolutional layer, or a transformed output (as was the case with the original implementation). Still, for sake of consistency with the paper, I have revised the code.
