### ISSUE TITLE
A puzzle

### ISSUE THREAD

**Issue by lasso007** [desh2608/crnn-relation-classification#4]
According to the paper "Learning local and global contexts using a convolutional recurrent network model for relation classification in biomedical text (Desh Raj, Sunil Kumar Sahu, and Ashish Anand)". In the file "crnn-relation-classification/source/crnn-att.py",
>W_a2 = tf.get_variable("W_a2", shape=[num_filters2, 1]) 

W_a2 is a matrix of  "num_filters2 x 1" size , but in your paper, it should be a  matrix of "num_filters2 x num_filters2" size. This is my puzzle, I wish your answer.

**Comment by desh2608** [comment]
The code is right. W_a2 should be a matrix of "num_filters2 x 1". This is a typo in the paper. Thanks for pointing this out.
