### ISSUE TITLE
glove_100d_w9_pubmed

### ISSUE THREAD

**Issue by blog4me** [desh2608/crnn-relation-classification#8]
hi,
    I've been finding this file for a couple of days, but I couldn't find it, could you plz tell me how to download it? Thanks a lot!

**Comment by desh2608** [comment]
I'm sorry it's not freely available. If you have access to the Pubmed journal corpus, you can train a GloVe model on that to get 100-dimensional word embeddings. See [here](https://nlp.stanford.edu/projects/glove/) for training GloVe vectors. If you don't have access to such a corpus, you can use the general GloVe vectors available on the linked website, but I'll warn you that the performance may get worse.

**Comment by blog4me** [comment]
well, it sucks...I'll find out if I have access to the Pubmed journal corpus. Thanks anyway.
